# Generated by Django 4.1.3 on 2023-03-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartInvigilationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invigilationstaffs',
            name='camera_no',
            field=models.CharField(max_length=200),
        ),
    ]
