# Generated by Django 4.1.3 on 2023-03-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartInvigilationApp', '0002_alter_invigilationstaffs_camera_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invigilationstaffs',
            name='camera_no',
            field=models.CharField(default='/videos/4.mp4', max_length=200),
        ),
    ]
